## Top 10 movies
or something i couldn't remember what the task was so..

#### TODO:
 - read data
 - filter data
 - that was simple enough

In [1]:
import pandas as pd

D:\setups\conda\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)

In [2]:
#Read csv file into a dataframe
df = pd.read_csv("movies.csv")

In [5]:
df.sort_values(by=['runtime'], inplace=True, ascending=False)
topTenRunTime = df[:10]
topTenRunTime

,budget,revenue,original_title,cast,director,runtime,genres,release_date,release_year
15,44000000,155760117,The Hateful Eight,Samuel L. Jackson|Kurt Russell|Jennifer Jason ...,Quentin Tarantino,167,Crime|Drama|Mystery|Western,12/25/15,2015
5,135000000,532950503,The Revenant,Leonardo DiCaprio|Tom Hardy|Will Poulter|Domhn...,Alejandro GonzÃ¡lez IÃ±Ã¡rritu,156,Western|Drama|Adventure|Thriller,12/25/15,2015
10,245000000,880674609,Spectre,Daniel Craig|Christoph Waltz|LÃ©a Seydoux|Ralp...,Sam Mendes,148,Action|Adventure|Crime,10/26/15,2015
40,28000000,201634991,Straight Outta Compton,O'Shea Jackson Jr.|Corey Hawkins|Jason Mitchel...,F. Gary Gray,147,Drama|Music,8/13/15,2015
33,40000000,162610473,Bridge of Spies,Tom Hanks|Mark Rylance|Amy Ryan|Alan Alda|Seba...,Steven Spielberg,141,Thriller|Drama,10/15/15,2015
7,108000000,595380321,The Martian,Matt Damon|Jessica Chastain|Kristen Wiig|Jeff ...,Ridley Scott,141,Drama|Adventure|Science Fiction,9/30/15,2015
14,280000000,1405035767,Avengers: Age of Ultron,Robert Downey Jr.|Chris Hemsworth|Mark Ruffalo...,Joss Whedon,141,Action|Adventure|Science Fiction,4/22/15,2015
4,190000000,1506249360,Furious 7,Vin Diesel|Paul Walker|Jason Statham|Michelle ...,James Wan,137,Action|Crime|Thriller,4/1/15,2015
89,50000000,3324330,Child 44,Tom Hardy|Gary Oldman|Noomi Rapace|Joel Kinnam...,Daniel Espinosa,137,Crime|Thriller,3/15/15,2015
3,200000000,2068178225,Star Wars: The Force Awakens,Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...,J.J. Abrams,136,Action|Adventure|Science Fiction|Fantasy,12/15/15,2015

### One month passes by now we have to plot stuff too...
- plot the top ten movie on a graph i guess

In [ ]:
import matplotlib.pyplot as plt